"""empty message

Revision ID: 9463f05f0050
Revises: c9ba3a867a2e
Create Date: 2025-07-03 17:41:33.524479

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9463f05f0050'
down_revision = 'c9ba3a867a2e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('brand', sa.String(length=120), nullable=False))
        batch_op.add_column(sa.Column('type', sa.String(length=120), nullable=False))
        batch_op.drop_column('model')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('model', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
        batch_op.drop_column('type')
        batch_op.drop_column('brand')

    # ### end Alembic commands ###
