"""empty message

Revision ID: a4e756430be7
Revises: ecc8190fd993
Create Date: 2025-07-15 00:45:09.184379

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a4e756430be7'
down_revision = 'ecc8190fd993'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_URL', sa.String(length=512), nullable=False))
        batch_op.add_column(sa.Column('public_id', sa.String(length=100), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_column('public_id')
        batch_op.drop_column('image_URL')

    # ### end Alembic commands ###
