"""empty message

Revision ID: a8ffa7c8adb7
Revises: a4e756430be7
Create Date: 2025-07-15 22:44:00.919762

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a8ffa7c8adb7'
down_revision = 'a4e756430be7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.alter_column('image_URL',
               existing_type=sa.VARCHAR(length=512),
               nullable=True)
        batch_op.alter_column('public_id',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.alter_column('public_id',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('image_URL',
               existing_type=sa.VARCHAR(length=512),
               nullable=False)

    # ### end Alembic commands ###
