"""empty message

Revision ID: ecc8190fd993
Revises: 9463f05f0050
Create Date: 2025-07-03 17:48:37.207198

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ecc8190fd993'
down_revision = '9463f05f0050'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_column('listed_price')
        batch_op.drop_column('store')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('store', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('listed_price', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
